### ISSUE TITLE
Consent PDF is wider than view 

### ISSUE THREAD

**Issue by ghost** [ResearchKit/AppCore#109]
Re: commit 12b4dfd3 (Implement onboarding manager)
https://github.com/ResearchKit/AppCore/pull/49/

We see that the consent pdf is wider than the view. May be an issue with css in html file, or some problem with the storyboard. 
![ios simulator screen shot jul 21 2015 2 04 49 pm](https://cloud.githubusercontent.com/assets/3868802/8814118/fa1c3576-2fbd-11e5-9f82-39ac01667b0c.png)

**Comment by p2** [comment]
I had the same problem: https://github.com/ResearchKit/ResearchKit/issues/243

Turns out this was refactored in ResearchKit and the HTML page body gets created around your consent. Our HTML documents now only include the content itself and the view sizes them correctly.

``` html
<h2>Overview</h2>
<p>
    Today’s mobile devices...
</p>
<p>
    ...
</p>
```

**Comment by ghost** [comment]
Closing as duplicate of ResearchKit/ResearchKit#243

**Comment by ghost** [comment]
@p2 thanks for this note.
