### ISSUE TITLE
#import "APCAppCore.h" where it's not necessary

### ISSUE THREAD

**Issue by p2** [ResearchKit/AppCore#16]
Both `APCTabBarViewController` and `APCPasscodeViewController` import all AppCore headers, making it impossible to use them outside of the whole bundle.

**Comment by p2** [comment]
Also, would it be possible to replace

```
[[UIStoryboard storyboardWithName:@"APCPasscode" bundle:[NSBundle appleCoreBundle]]
```

with

```
[[UIStoryboard storyboardWithName:@"APCPasscode" bundle:[NSBundle bundleForClass:[self class]]]
```

I'm not sure why the storyboard is made dependent on a specific bundle key.

**Comment by jwe-apple** [comment]
Same - please submit as a PR and I'll have someone review it!

**Comment by p2** [comment]
I'm running into more of these as I integrate, happy to send a PR once I'm through.

**Comment by p2** [comment]
A lot of the view controllers depend on `APCAppDelegate`. I have moved the methods accessed into a protocol that APCAppDelegate adopts, and my own app delegate as well. Since to get this to work on my end I have to follow this path throughout and I'm doing this while I'm removing all the AppCore.h imports.

Should I or should I not commit this to this branch?

The protocol currently is:

``` obj-c
@protocol APCAppDelegateTasks <NSObject>

@required
@property (copy, nonatomic, readonly) NSDictionary *__nullable initializationOptions;

@property (strong, nonatomic, readonly) APCDataSubstrate *__nullable dataSubstrate;

@property (strong, nonatomic, readonly) APCOnboarding *__nullable onboarding;

- (void)instantiateOnboardingForType:(APCOnboardingTaskType)type;

@end
```

**Comment by jwe-apple** [comment]
I'd lean toward getting the first PR accepted, then submitting it as a follow-on.

**Comment by p2** [comment]
I'll keep it piling up on my master branch, can later cherry-pick.
