### ISSUE TITLE
APCDataSubstrate depends on category methods during initialization

### ISSUE THREAD

**Issue by p2** [ResearchKit/AppCore#30]
During initialization, `APCDataSubstrate` initializes its CoreData stack and a HKStore handle. These methods are defined in the categories `CoreData` and `HealthKit`, which makes for neat code separation but technically is not suitable for a category.

**Comment by jwe-apple** [comment]
This is actually ok as long as they are always built together (which they are, if you build APCAppCore as a whole). Could see an argument for merging them all into one h/m pair but retaining the category separation, but don't think it's a strong one. If you're cherry-picking files into another project, why not just pick them all?

**Comment by p2** [comment]
I find it strange that a class cannot live without categories of itself. Sure, I can include them all, but since it's not that much code (HealthKit is a one-line method) I'm not sure this separation is needed.

**Comment by jwe-apple** [comment]
Happy to accept a PR for this.
