### ISSUE TITLE
SBBProfileViewController comparison looks odd

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/AppCore#37]
Code uses the following comparison:

`self.user.sharedOptionSelection != [NSNumber numberWithInteger:SBBConsentShareScopeNone]`

This looks unlikely to be what's intended.

**Comment by p2** [comment]
To be able to reuse `APCSharingOptionsViewController` I'd make a new APCUser property, which could be an enum that can be mapped to `SBBConsentShareScopeXy`. Should I do that on a separate branch or the one I'm working on for #43 , where I'm converting APCUser to a protocol?

Edit: meaning this would also resolve this issue.

Edit 2: Oh wait, just realized I'm not actually using `APCSharingOptionsViewController` but a good old `ORKConsentSharingStep`.
