### ISSUE TITLE
Move onboarding configuration to an onboarding manager

### ISSUE THREAD

**Issue by p2** [ResearchKit/AppCore#48]
Similar to #47, code used to setup and configure onboarding could be moved to a **onboarding manager class**. This would free up the app delegate and allow for easy customization by subclassing. For simple tie in to the app, AppCore may ask the app delegate, via protocol, for the onboarding manager.

I'm not sure if onboarding should be rolled into consenting or stay separate. It seems to me keeping them separate is desirable so as to not create a huge manager class with slightly different responsibilities.

Also cf. #41

**Comment by peculiar** [comment]
My vote is to make onboarding a separate concept from consent; consent will vary wildly from study to study.

**Comment by p2** [comment]
BTW this is being worked on in PR https://github.com/ResearchKit/AppCore/pull/49

**Comment by p2** [comment]
This has been implemented with #49 .
