### ISSUE TITLE
New project with RK, AppCore and BridgeSDK has build error

### ISSUE THREAD

**Issue by a-dogan** [ResearchKit/AppCore#53]
Hi, 
When I create a new iOS project using latest of ResearchKit framework, AppCore and BridgeSDK has build errors and can't be built.

/AppCore/APCAppCore/APCAppCore/DataSubstrate/Model/APCSmartSurveyTask.m:99:68: Property 'questions' not found on object of type 'SBBSurvey *'

/AppCore/APCAppCore/APCAppCore/DataSubstrate/Model/APCSmartSurveyTask.m:438:18: Property 'detail' not found on object of type 'SBBSurveyQuestion *'

/AppCore/APCAppCore/APCAppCore/DataSubstrate/Model/APCSmartSurveyTask.m:439:33: Property 'detail' not found on object of type 'SBBSurveyQuestion *'

/AppCore/APCAppCore/APCAppCore/Startup/APCAppDelegate.m:90:31: Unknown type name 'APCDemographicUploader'

/AppCore/APCAppCore/APCAppCore/Startup/APCAppDelegate.m:90:1: Property with 'retain (or strong)' attribute must be of object type

/AppCore/APCAppCore/APCAppCore/DataSubstrate/Model/APCSmartSurveyTask.m:572:50: No known class method for selector 'scaleAnswerFormatWithMaxValue:minValue:step:defaultValue:'

**Comment by peculiar** [comment]
Some of the errors you're reporting typical show up if the wrong BridgeSDK branch is used. Please ensure you're using the rk-compat branch.

A PR for Demographic Uploader will be forthcoming. Until then, just comment out the lines that instantiate APCDemographicUploader.

**Comment by a-dogan** [comment]
Closing. I was able to resolve after pulling correct BridgeSDK branch rk-compat.
