### ISSUE TITLE
Getting a "code object is not signed at all" error... Anyone else having this issue?

### ISSUE THREAD

**Issue by ryanchan002** [ResearchKit/AppCore#62]
Project builds and runs, but I get this error when trying to submit to the app store. Any ideas? I have been going crazy for the past day trying to get this submitted and have tried a lot of different things without any luck...

Thanks for your help

**Comment by peculiar** [comment]
Sounds like there's a *.sh file being included in the target membership. If so, just deselect in tin the Target Membership pane. If it's in AppCore then it should obviously be fixed.

**Comment by ryanchan002** [comment]
You are honestly a god send!!! THANK YOU so much I was pulling my hair out for a full day...

APCAppCore/Resources/get_debug_ip_address.sh was the culprit causing the issue. You were totally right about that .sh file being included in the target membership. Might want to fix for future releases. 

THANKS AGAIN!

**Comment by peculiar** [comment]
This issue is addressed in https://github.com/ResearchKit/AppCore/pull/55
