### ISSUE TITLE
APCPasscodeViewController does not reset input blobs on success

### ISSUE THREAD

**Issue by p2** [ResearchKit/AppCore#93]
`APCPasscodeViewController` disappears when the PIN is entered correctly. If it is subsequently shown again the 4 input indicators are still blobs, not dashes.

This can be resolved by deallocating APCPasscodeViewController when PIN entry succeeds, however in the reference implementation in APCAppDelegate this is not the case as it's being retained (https://github.com/ResearchKit/AppCore/blob/master/APCAppCore/APCAppCore/Startup/APCAppDelegate.m#L975).

**Comment by ghost** [comment]
@p2  Should be fixed after this merge. Thanks.
